language: python
python:
  - "3.4"
install:
  - pip install -e .
  - pip install coveralls
  - pip install flake8
  - pip install typing  # setup.py doesn't seem to be working
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls